# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NightView', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=20),
        ),
    ]
